apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-v1.0.0
  namespace: default 
  labels: 
    release: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - name: web-01
        image: vinayjadhav/app:v1.0.0
        ports:
          - containerPort: 8080
            name: www
      livenessProbe:
        httpGet:
          path: /live
          port: www
        initialDelaySeconds: 10
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /ready
          port: www
        initialDelaySeconds: 10
        periodSeconds: 5

---
apiVersion: v1 
kind: Service
metadata:
  name: svc-web-app
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: spring-boot
  type: NodePort